/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-12-11 10:19:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import Dao.CartItemDAO;
import Entity.CartItem;
import java.sql.SQLException;
import Dao.DigitalSignatureDAO;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(5);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.SQLException");
    _jspx_imports_classes.add("Entity.CartItem");
    _jspx_imports_classes.add("Dao.CartItemDAO");
    _jspx_imports_classes.add("Dao.DigitalSignatureDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("    <title>Giỏ hàng của bạn</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/bds.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .u-lo li {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            z-index: 10; /* Đảm bảo menu cha hiển thị trên cùng */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul li a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Thiết lập cho menu con */\r\n");
      out.write("        ul li ul {\r\n");
      out.write("            display: none; /* Ẩn menu con mặc định */\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 100%;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("            min-width: 200px;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            z-index: 999; /* Đảm bảo menu con hiển thị trên các phần tử khác */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul li ul li {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        ul li ul li a {\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hiển thị menu con khi hover */\r\n");
      out.write("        ul li:hover ul {\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Style cho menu con khi hover */\r\n");
      out.write("        ul li ul li a:hover {\r\n");
      out.write("            background-color: #eee;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-content {\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 24px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Container for cart items */\r\n");
      out.write("        .container.mt-4 {\r\n");
      out.write("            max-width: 1200px; /* Limit the width for larger screens */\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* List of cart items */\r\n");
      out.write("        .list-group {\r\n");
      out.write("            list-style-type: none;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Individual product item styling */\r\n");
      out.write("        .list-group-item {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* On hover, slightly enlarge the product card */\r\n");
      out.write("        .list-group-item:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Styling for product image */\r\n");
      out.write("        .list-group-item img {\r\n");
      out.write("            width: 150px;  /* Larger image */\r\n");
      out.write("            height: 150px;  /* Maintain aspect ratio */\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Styling for the description part (title, price, etc.) */\r\n");
      out.write("        .list-group-item div {\r\n");
      out.write("            flex-grow: 1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Title styling */\r\n");
      out.write("        .list-group-item h5 {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Address and area styling */\r\n");
      out.write("        .list-group-item p {\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Price styling */\r\n");
      out.write("        .list-group-item .text-danger {\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Button to remove item */\r\n");
      out.write("        .btn.btn-sm.btn-danger {\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            background-color: #d9534f;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            padding: 5px 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn.btn-sm.btn-danger:hover {\r\n");
      out.write("            background-color: #a94442;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Checkout button styling */\r\n");
      out.write("        #checkout-button {\r\n");
      out.write("            background-color: #5cb85c;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #checkout-button:hover {\r\n");
      out.write("            background-color: #4cae4c;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-item .price, .cart-item .area {\r\n");
      out.write("            color: #d9534f; /* Màu đỏ */\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    Integer userId = (Integer) session.getAttribute("userId");
    List<CartItem> cartItems = null;

    if (userId != null) {
        CartItemDAO cartItemDAO = new CartItemDAO();
        try {
            cartItems = cartItemDAO.getCartItemsByUserId(userId);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <div class=\"header-top\" style=\"width: 100%; position: sticky; top: 0; z-index: 1000;\">\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("                <img src=\"jpg/phone-call.png\" class=\"icon\">\r\n");
      out.write("                <span>0123 456 789</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("                <img src=\"jpg/email.png\" class=\"icon\">\r\n");
      out.write("                <span>info@company.com</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"jpg/location.png\" class=\"icon\">\r\n");
      out.write("                <span>123 Đường ABC, Quận XYZ, TP.HCM</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            boolean isLoggedIn = session.getAttribute("username") != null;
            String username = (String) session.getAttribute("username");
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-right\" style=\"margin-top: 10px\">\r\n");
      out.write("            ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("            <a href=\"account.jsp\" class=\"btn\">\r\n");
      out.write("                <h3 style=\"white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px;\">\r\n");
      out.write("                    Hello, ");
      out.print( username );
      out.write("\r\n");
      out.write("                </h3>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0)\" id=\"logoutButton\" class=\"btn\" onclick=\"document.getElementById('logoutForm').submit();\">\r\n");
      out.write("                <h3>Đăng xuất</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Hidden Form to Logout -->\r\n");
      out.write("            <form id=\"logoutForm\" action=\"logout\" method=\"POST\" style=\"display: none;\">\r\n");
      out.write("                <button type=\"submit\" style=\"display: none;\"></button> <!-- This button will not be visible -->\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn\"><h3>Đăng nhập</h3></a>\r\n");
      out.write("            <a href=\"register.jsp\" class=\"btn\"><h3>Đăng ký</h3></a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <a href=\"create-poster.jsp\" class=\"btn\"><h3>Đăng tin</h3></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"store-name\">\r\n");
      out.write("                <h1><a href=\"welcome\">\r\n");
      out.write("                    <span class=\"color1\">HOME</span>\r\n");
      out.write("                    <span class=\"color2\">LANDER</span> <!-- Đổi từ VINA BOOK sang VINA BĐS -->\r\n");
      out.write("                </a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"u-lo\">\r\n");
      out.write("                    <li><a href=\"forsale\">Nhà Đất Bán</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Thông tin bán nhà đất</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Mua bán bất động sản</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Nhà đất giá rẻ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"forrent\">Nhà Đất Cho Thuê</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Thông tin cho thuê nhà đất</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Thuê nhà nguyên căn</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Thuê căn hộ giá rẻ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"Project\">Dự Án</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Các dự án nổi bật</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Dự án nhà ở</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Dự án chung cư</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"news.jsp\">Tin Tức</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Tin thị trường</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Xu hướng bất động sản</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Phân tích và đánh giá</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"wiki.jsp\">Wiki BĐS</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Mua bán</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Cho thuê</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Tài chính</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Phong thủy</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-info\">\r\n");
      out.write("                <img src=\"jpg/phone-call.png\" alt=\"Phone Icon\" class=\"phone-icon\">\r\n");
      out.write("                <span class=\"phone-number\">0123 456 789</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("    <h3 class=\"text-center mb-4\">Giỏ hàng của bạn</h3>\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"list-group\">\r\n");
      out.write("        ");

            boolean hasItemsInCart = cartItems != null && !cartItems.isEmpty();
            if (hasItemsInCart) {
                for (CartItem item : cartItems) {
        
      out.write("\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <div class=\"d-flex align-items-center\">\r\n");
      out.write("                <!-- Image is wrapped in an anchor tag for redirection -->\r\n");
      out.write("                <a href=\"property-detail.jsp?id=");
      out.print( item.getPropertyId() );
      out.write("\" style=\"cursor: pointer;\">\r\n");
      out.write("                    <img src=\"");
      out.print( item.getImageUrl() );
      out.write("\" alt=\"");
      out.print( item.getTitle() );
      out.write("\" class=\"img-thumbnail mr-3\"\r\n");
      out.write("                         style=\"width: 100px; height: 100px; object-fit: cover;\">\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h5 class=\"mb-1\">");
      out.print( item.getTitle() );
      out.write("</h5>\r\n");
      out.write("                    <p class=\"mb-1 text-muted\"><i class=\"fas fa-map-marker-alt\"></i> Địa chỉ: ");
      out.print( item.getAddress() );
      out.write("</p>\r\n");
      out.write("                    <p class=\"mb-1\"><i class=\"fas fa-ruler-combined\"></i> Diện tích: <strong>");
      out.print( item.getArea() );
      out.write(" m²</strong></p>\r\n");
      out.write("                    <p class=\"mb-0 text-danger\"><i class=\"fas fa-dollar-sign\"></i> Giá: <strong>");
      out.print( item.getPrice() );
      out.write(" tỷ</strong></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Remove button (form to delete product) -->\r\n");
      out.write("            <form action=\"removeItemFromCart\" method=\"POST\" style=\"display: inline;\">\r\n");
      out.write("                <input type=\"hidden\" name=\"propertyId\" value=\"");
      out.print( item.getPropertyId() );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-sm btn-danger ml-3\" onclick=\"return confirm(' Bạn có chắc chắn muốn xóa bất động sản này không?')\">\r\n");
      out.write("                    <i class=\"fas fa-trash-alt\"></i> Xóa\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </li>\r\n");
      out.write("        ");

            }
        } else {
        
      out.write("\r\n");
      out.write("        <li class=\"list-group-item text-center text-muted\">Giỏ hàng của bạn đang trống.</li>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </ul>\r\n");




      out.write("\r\n");
      out.write("    <button id=\"checkout-button\" class=\"btn btn-success w-100 mt-3\" onclick=\"window.location.href='checkout.jsp';\">Đặt Hàng</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    function checkCartBeforeCheckout() {\r\n");
      out.write("        // Check if there are items in the cart by checking the cart content message\r\n");
      out.write("        const emptyCartMessage = document.querySelector('.list-group-item.text-muted');\r\n");
      out.write("\r\n");
      out.write("        if (emptyCartMessage) {\r\n");
      out.write("            // Cart is empty\r\n");
      out.write("            alert('Giỏ hàng của bạn hiện tại không có sản phẩm. Vui lòng thêm sản phẩm vào giỏ hàng để tiếp tục.');\r\n");
      out.write("        } else {\r\n");
      out.write("            // Proceed to checkout if there are items\r\n");
      out.write("            window.location.href = 'checkout.jsp';\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Disable the checkout button initially if the cart is empty\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        const checkoutButton = document.getElementById('checkout-button');\r\n");
      out.write("        const emptyCartMessage = document.querySelector('.list-group-item.text-muted');\r\n");
      out.write("\r\n");
      out.write("        if (emptyCartMessage) {\r\n");
      out.write("            checkoutButton.disabled = true; // Disable button if cart is empty\r\n");
      out.write("            checkoutButton.style.backgroundColor = '#ccc'; // Change color to indicate disabled state\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("\r\n");
      out.write("        <h1><a href=\"homes\">\r\n");
      out.write("            <span class=\"color1\">HOME</span>\r\n");
      out.write("            <span class=\"color2\">LANDER</span>\r\n");
      out.write("        </a></h1>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-phone\"></i> Hotline: 0123 456 789</span>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-envelope\"></i> Hỗ trợ: support@batdongsan.com</span>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-headset\"></i> Chăm sóc: 0987 654 321</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("        <!-- Thông tin công ty -->\r\n");
      out.write("        <div class=\"company-info\">\r\n");
      out.write("            <h3>Công ty Bất Động Sản</h3>\r\n");
      out.write("            <p>Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM</p>\r\n");
      out.write("            <p>Điện thoại: 0123 456 789</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Liên kết nhanh -->\r\n");
      out.write("        <div class=\"quick-links\">\r\n");
      out.write("            <h3>Liên kết nhanh</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dự án</a></li>\r\n");
      out.write("                <li><a href=\"#\">Tin tức</a></li>\r\n");
      out.write("                <li><a href=\"#\">Liên hệ</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mạng xã hội -->\r\n");
      out.write("        <div class=\"social-media\">\r\n");
      out.write("            <h3>Mạng xã hội</h3>\r\n");
      out.write("            <a href=\"https://www.facebook.com/khoa.ngo.562114/\" class=\"social-icon\"><i class=\"fab fa-facebook\"></i>\r\n");
      out.write("                Facebook</a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/khoa5462/\" class=\"social-icon\"><i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                Instagram</a>\r\n");
      out.write("            <a href=\"https://mail.google.com/mail/u/0/?hl=vi#inbox\" class=\"social-icon\"><i\r\n");
      out.write("                    class=\"fas fa-envelope\"></i>\r\n");
      out.write("                Mail</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Form nhập email -->\r\n");
      out.write("        <div class=\"newsletter\">\r\n");
      out.write("            <h3>Đăng ký nhận tin tức mới nhất</h3>\r\n");
      out.write("            <form action=\"#\" method=\"POST\">\r\n");
      out.write("                <input type=\"email\" name=\"email\" placeholder=\"Nhập email của bạn\" required>\r\n");
      out.write("                <button type=\"submit\">Đăng ký</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("        <p>&copy; 2024 Công ty Bất Động Sản. Mọi quyền lợi thuộc về công ty.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
