/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-12-11 10:19:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Entity.Property;
import java.util.List;
import Dao.PropertyDAO;
import Entity.Property1;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("Dao.PropertyDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Entity.Property");
    _jspx_imports_classes.add("Entity.Property1");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bds.css\">\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>Trang JSP với UTF-8</title>\r\n");
      out.write("</head>\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <div class=\"header-top\" style=\"width: 100%; position: sticky; top: 0; z-index: 1000;\">\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("                <img src=\"jpg/phone-call.png\" class=\"icon\">\r\n");
      out.write("                <span>098 664 1965</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("                <img src=\"jpg/email.png\" class=\"icon\">\r\n");
      out.write("                <span>khoangoquan@gmail.com</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"contact-item\">\r\n");
      out.write("\r\n");
      out.write("                <img src=\"jpg/location.png\" class=\"icon\">\r\n");
      out.write("                <span>123 Đường 12, Quận 9, TP.HCM</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            Integer userId = (Integer) session.getAttribute("userId");
            String username = (String) session.getAttribute("username");
            boolean isLoggedIn = userId != null;
        
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header-right\" style=\"margin-top: 10px\">\r\n");
      out.write("            ");
 if (isLoggedIn) { 
      out.write("\r\n");
      out.write("            <a href=\"account.jsp\" class=\"btn\">\r\n");
      out.write("                <h3 style=\"white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 150px;\">\r\n");
      out.write("                    Hello, ");
      out.print( username );
      out.write("\r\n");
      out.write("                </h3>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"javascript:void(0)\" id=\"logoutButton\" class=\"btn\"\r\n");
      out.write("               onclick=\"document.getElementById('logoutForm').submit();\">\r\n");
      out.write("                <h3>Đăng xuất</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <!-- Hidden Form to Logout -->\r\n");
      out.write("            <form id=\"logoutForm\" action=\"logout\" method=\"POST\" style=\"display: none;\">\r\n");
      out.write("                <button type=\"submit\" style=\"display: none;\"></button> <!-- This button will not be visible -->\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <!-- Display login and registration options if not logged in -->\r\n");
      out.write("            <a href=\"login.jsp\" class=\"btn\">\r\n");
      out.write("                <h3>Đăng nhập</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"register.jsp\" class=\"btn\">\r\n");
      out.write("                <h3>Đăng ký</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- \"Post Status\" button, visible to both logged-in and non-logged-in users -->\r\n");
      out.write("            <a href=\"post-status.jsp\" class=\"btn\">\r\n");
      out.write("                <h3>Đăng tin</h3>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <a href=\"#\" class=\"floating-cart\" id=\"floating-cart\" onclick=\"toggleMiniCart()\"\r\n");
      out.write("       style=\"border: 1px solid #ccc; border-radius:100%;\">\r\n");
      out.write("        <img src=\"jpg/heart%20(1).png\" style=\"width: 30px!important; height: 30px !important;\" alt=\"Giỏ hàng\"\r\n");
      out.write("             class=\"cart-icon\">\r\n");
      out.write("        <div class=\"item-count\">0</div>\r\n");
      out.write("        <div class=\"mini-cart\">\r\n");
      out.write("            <h4>Bất động sản đã lưu</h4>\r\n");
      out.write("            <ul id=\"cart-items\"></ul>\r\n");
      out.write("            <button id=\"go-to-cart\" onclick=\"goToCart()\">Đi tới xem bất động sản đã lưu</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu\">\r\n");
      out.write("        <div class=\"header-bottom\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"store-name\">\r\n");
      out.write("                <h1><a href=\"\">\r\n");
      out.write("                    <span class=\"color1\">HOME</span>\r\n");
      out.write("                    <span class=\"color2\">LANDER</span>\r\n");
      out.write("                </a></h1>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"u-lo\">\r\n");
      out.write("                    <li><a href=\"forsale\">Nhà Đất Bán</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Thông tin bán nhà đất</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Mua bán bất động sản</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Nhà đất giá rẻ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"forrent\">Nhà Đất Cho Thuê</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Thông tin cho thuê nhà đất</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Thuê nhà nguyên căn</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Thuê căn hộ giá rẻ</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"Project\">Dự Án</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Các dự án nổi bật</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Dự án nhà ở</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Dự án chung cư</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"news.jsp\">Tin Tức</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Tin thị trường</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Xu hướng bất động sản</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Phân tích và đánh giá</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"wiki.jsp\">Wiki BĐS</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\">Mua bán</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Cho thuê</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Tài chính</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Phong thủy</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"contact-info\">\r\n");
      out.write("                <img src=\"jpg/phone-call.png\" alt=\"Phone Icon\" class=\"phone-icon\">\r\n");
      out.write("                <span class=\"phone-number\">0123 456 789</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"slideshow-container\">\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"jpg/1%20(1).webp\" alt=\"Banner 1\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"jpg/20.jpg\" alt=\"Banner 2\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"search-container\">\r\n");
      out.write("        <form class=\"search-form\" id=\"search-form\" method=\"post\" action=\"SearchServlet\">\r\n");
      out.write("            <input type=\"text\" id=\"search\" placeholder=\"Tìm kiếm sản phẩm...\" name=\"search\" required>\r\n");
      out.write("            <input type=\"text\" id=\"city\" placeholder=\"Tìm kiếm theo địa chỉ...\" name=\"city\">\r\n");
      out.write("            <button type=\"submit\">Tìm Kiếm</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        function toggleDropdown(dropdownClass) {\r\n");
      out.write("            const dropdown = document.querySelector(`.${dropdownClass}`);\r\n");
      out.write("            dropdown.classList.toggle('hidden');\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"JS/script.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#search, #city').on('keyup', function () {\r\n");
      out.write("                var searchText = $('#search').val();\r\n");
      out.write("                var city = $('#city').val();\r\n");
      out.write("\r\n");
      out.write("                if (searchText.length > 0 || city.length > 0) {\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                        url: 'SearchServlet',\r\n");
      out.write("                        type: 'POST',\r\n");
      out.write("                        data: {\r\n");
      out.write("                            search: searchText,\r\n");
      out.write("                            city: city\r\n");
      out.write("                        },\r\n");
      out.write("                        success: function (response) {\r\n");
      out.write("                            // Hiển thị kết quả trả về trong phần product-list\r\n");
      out.write("                            $('#search-results').html(response);\r\n");
      out.write("                        },\r\n");
      out.write("                        error: function () {\r\n");
      out.write("                            $('#search-results').html('<p>Lỗi trong quá trình tìm kiếm.</p>');\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                } else {\r\n");
      out.write("                    $('#search-results').html('');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<div class=\"product-section\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"product-list\" id=\"search-results\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"news-section\">\r\n");
      out.write("    <h2>Tin Tức Bất Động Sản</h2>\r\n");
      out.write("\r\n");
      out.write("    <!-- Danh mục -->\r\n");
      out.write("    <ul class=\"news-categories\">\r\n");
      out.write("        <li><a href=\"#\">Tin nổi bật</a></li>\r\n");
      out.write("        <li><a href=\"#\">BĐS TP.HCM</a></li>\r\n");
      out.write("        <li><a href=\"#\">BĐS Hà Nội</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <!-- List các tin tức -->\r\n");
      out.write("    <div class=\"news-list\">\r\n");
      out.write("        <div class=\"news-item\">\r\n");
      out.write("            <img src=\"jpg/HaNoi.jpg\" alt=\"Image\">\r\n");
      out.write("            <h3><a href=\"#\">Đất Hà Nội tăng giá mạnh </a></h3>\r\n");
      out.write("            <p class=\"summary\">Hà Nội có tiền cũng không mua đất đuược?...</p>\r\n");
      out.write("            <span class=\"date\">Ngày đăng: 01/01/2024</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"news-item\">\r\n");
      out.write("            <img src=\"jpg/HCM.jpg\" alt=\"Image\">\r\n");
      out.write("            <h3><a href=\"#\">HCM ngày càng xấu đi trong mắt du khách nuước ngoài</a></h3>\r\n");
      out.write("            <p class=\"summary\">Người nước ngoài kêu ca về du lịch...</p>\r\n");
      out.write("            <span class=\"date\">Ngày đăng: 01/01/2024</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"news-item\">\r\n");
      out.write("            <img src=\"jpg/binhduong.jpg\" alt=\"Image\">\r\n");
      out.write("            <h3><a href=\"#\">Bình Dương thành phố mới</a></h3>\r\n");
      out.write("            <p class=\"summary\">Thành phố trong thành phố...</p>\r\n");
      out.write("            <span class=\"date\">Ngày đăng: 01/01/2024</span>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"product-section\">\r\n");
      out.write("    <h2 style=\"text-align: center;\">\r\n");
      out.write("        Bất động sản dành cho bạn </h2>\r\n");
      out.write("    <div style=\"text-align: center; font-size: 14px; margin-bottom: 20px;margin-left: 660px\">\r\n");
      out.write("        <a href=\"forsale\" style=\"margin-right: 20px; text-decoration: none; color: darkred;\">\r\n");
      out.write("            Tin nhà đất bán mới nhất\r\n");
      out.write("        </a>\r\n");
      out.write("        |\r\n");
      out.write("        <a href=\"forrent\" style=\"margin-left: 20px; text-decoration: none; color: darkred;\">\r\n");
      out.write("            Tin nhà đất cho thuê mới nhất\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"product-list\">\r\n");
      out.write("        ");

            List<Property> properties = (List<Property>) request.getAttribute("properties");
            if (properties != null && !properties.isEmpty()) {
                int index = properties.size() - 1;  // Lấy chỉ số cuối cùng của danh sách
                for (int i = index; i >= 0; i--) {
                    Property property = properties.get(i);

                    // Kiểm tra trạng thái bất động sản (nếu status = "0", không hiển thị)
                    if ("0".equals(property.getStatus())) {
                        continue; // Bỏ qua sản phẩm có status = 0
                    }
        
      out.write("\r\n");
      out.write("        <div class=\"product-item\" ");
      out.print( i >= 8 ? "style='display: none;'" : "" );
      out.write(" >\r\n");
      out.write("        <span onclick=\"location.href='property-detail.jsp?id=");
      out.print( property.getId() );
      out.write("'\"\r\n");
      out.write("              style=\"cursor: pointer; color: blue; text-decoration: none;\">\r\n");
      out.write("            <img src=\"");
      out.print( property.getImageUrl() );
      out.write("\" alt=\"");
      out.print( property.getTitle() );
      out.write("\" class=\"product-image\">\r\n");
      out.write("            <h3>");
      out.print( property.getTitle() );
      out.write("</h3>\r\n");
      out.write("            <p class=\"address\">\r\n");
      out.write("                <img src=\"jpg/location.png\" alt=\"Location Icon\" class=\"location-icon\">\r\n");
      out.write("                ");
      out.print( property.getAddress() );
      out.write("\r\n");
      out.write("            </p>\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("                <div class=\"price-size\">\r\n");
      out.write("                    <p class=\"price\">");
      out.print( property.getPrice() );
      out.write(" tỷ</p>\r\n");
      out.write("                    <p class=\"size\">");
      out.print( property.getArea() );
      out.write(" m²</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </span>\r\n");
      out.write("            <div class=\"heart-icon\" onclick=\"checkLogin()\">\r\n");
      out.write("                <img src=\"jpg/heartred.png\"  alt=\"Heart Icon\" class=\"heart-image\">\r\n");
      out.write("                <span class=\"favorite-text\">Bấm vào đây để lưu tin</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                function checkLogin() {\r\n");
      out.write("                    alert('Vui lòng đăng nhập để lưu tin.');\r\n");
      out.write("                    window.location.href = 'login.jsp';\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

                }
            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Nút xem thêm và ẩn bớt -->\r\n");
      out.write("    <div class=\"view-more\">\r\n");
      out.write("        <a href=\"#\" id=\"toggleButton\">Xem thêm</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        const toggleButton = document.getElementById('toggleButton');\r\n");
      out.write("        const products = document.querySelectorAll('.product-item');\r\n");
      out.write("        let isExpanded = false; // Trạng thái để theo dõi việc mở rộng hay thu gọn\r\n");
      out.write("\r\n");
      out.write("        // Ban đầu hiển thị 8 sản phẩm đầu tiên\r\n");
      out.write("        products.forEach((product, index) => {\r\n");
      out.write("            if (index < 8) {\r\n");
      out.write("                product.style.display = 'block'; // Hiển thị 8 sản phẩm đầu tiên\r\n");
      out.write("            } else {\r\n");
      out.write("                product.style.display = 'none'; // Ẩn các sản phẩm còn lại\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        toggleButton.addEventListener('click', function (e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("            if (isExpanded) {\r\n");
      out.write("                // Khi trạng thái đang mở rộng, thu gọn lại và chỉ hiển thị 8 sản phẩm\r\n");
      out.write("                products.forEach((product, index) => {\r\n");
      out.write("                    if (index >= 8) {\r\n");
      out.write("                        product.style.display = 'none'; // Ẩn các sản phẩm ngoài 8 sản phẩm đầu tiên\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                toggleButton.textContent = 'Xem thêm'; // Đổi lại thành \"Xem thêm\"\r\n");
      out.write("            } else {\r\n");
      out.write("                // Khi trạng thái đang thu gọn, hiển thị tất cả sản phẩm\r\n");
      out.write("                products.forEach(product => product.style.display = 'block'); // Hiển thị tất cả sản phẩm\r\n");
      out.write("                toggleButton.textContent = 'Ẩn bớt'; // Đổi thành \"Ẩn bớt\"\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            // Đảo trạng thái\r\n");
      out.write("            isExpanded = !isExpanded;\r\n");
      out.write("\r\n");
      out.write("            // Thực hiện cuộn mượt mà về đầu phần sản phẩm\r\n");
      out.write("            document.querySelector('.product-section').scrollIntoView({\r\n");
      out.write("                behavior: 'smooth',\r\n");
      out.write("                block: 'start'\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    .favorite-text {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -25px; /* Đưa văn bản xuống dưới trái tim */\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%); /* Căn giữa văn bản với trái tim */\r\n");
      out.write("        visibility: hidden; /* Ẩn văn bản mặc định */\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        padding: 5px 10px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 12px;\r\n");
      out.write("        white-space: nowrap; /* Ngừng việc gãy dòng */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .heart-icon:hover .favorite-text {\r\n");
      out.write("        visibility: visible; /* Hiển thị khi hover vào icon trái tim */\r\n");
      out.write("    }\r\n");
      out.write("    /* Basic styling */\r\n");
      out.write("    .featured-properties-section {\r\n");
      out.write("        max-width: 85%;\r\n");
      out.write("        margin-left: 95px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        margin-bottom: 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-list-container {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        overflow-x: auto;\r\n");
      out.write("        scroll-behavior: smooth;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-card {\r\n");
      out.write("        flex: 0 0 200px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-card p {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-family: Arial;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-card img {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: auto;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-card:hover {\r\n");
      out.write("        transform: translateY(-10px); /* Lift the card slightly */\r\n");
      out.write("        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3); /* Increase shadow */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Navigation buttons */\r\n");
      out.write("    .navigation-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navigation-button {\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 8px 12px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navigation-button:disabled {\r\n");
      out.write("        background-color: #ccc;\r\n");
      out.write("        cursor: not-allowed;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .property-list-container::-webkit-scrollbar {\r\n");
      out.write("        display: none; /* For Chrome, Safari, and Edge */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Tạo danh sách các thành phố lớn
    List<String> majorCities = List.of("TP.HCM", "Hà Nội", "Đà Nẵng", "Vũng Tàu");

    // Lấy danh sách bất động sản từ các thành phố này
    PropertyDAO propertyDAO = new PropertyDAO();
    List<Property1> properties1 = propertyDAO.getPropertiesByCities(majorCities);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"featured-properties-section\">\r\n");
      out.write("    <h2>Dự án bất động sản nổi bật</h2>\r\n");
      out.write("    <div class=\"navigation-buttons\">\r\n");
      out.write("        <button class=\"navigation-button\" id=\"prevButton\">⬅️ Trước</button>\r\n");
      out.write("        <button class=\"navigation-button\" id=\"nextButton\">Tiếp ➡️</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"property-list-container\" id=\"productList\">\r\n");
      out.write("        <!-- Hiển thị danh sách bất động sản -->\r\n");
      out.write("        ");

            if (properties1 != null && !properties1.isEmpty()) {
                for (Property1 property : properties1) {
                    // Tách địa chỉ theo dấu ','
                    String[] addressParts = property.getAddress().split(",");
                    String cityPart = "";
                    String preCityWord = "";

                    // Kiểm tra và lấy tên thành phố
                    if (addressParts.length > 0) {
                        cityPart = addressParts[addressParts.length - 1].trim(); // Thành phố
                        if (addressParts.length > 1) {
                            preCityWord = addressParts[addressParts.length - 2].trim(); // Từ trước thành phố
                        }
                    }
        
      out.write("\r\n");
      out.write("        <div class=\"property-card\">\r\n");
      out.write("            <a href=\"property-detail.jsp?id=");
      out.print( property.getId() );
      out.write("\" style=\"text-decoration: none; color: inherit;\">\r\n");
      out.write("                <img src=\"");
      out.print( property.getImageUrl() );
      out.write("\" alt=\"");
      out.print( property.getTitle() );
      out.write("\"\r\n");
      out.write("                     style=\"width: 100%; height: auto;\">\r\n");
      out.write("                <h3>");
      out.print( property.getTitle() );
      out.write("\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p>\r\n");
      out.write("                    ");
      out.print( property.getDescription().length() > 50 ? property.getDescription().substring(0, 50) + "..." : property.getDescription() );
      out.write("\r\n");
      out.write("                </p>\r\n");
      out.write("                <div style=\"display: flex; justify-content: space-between; color: red; margin-top: 5px;\">\r\n");
      out.write("                    <span>");
      out.print( property.getArea() );
      out.write(" m²</span>\r\n");
      out.write("                    <span><i class=\"fas fa-map-marker-alt\"></i> ");
      out.print( preCityWord + ", " + cityPart );
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            }
        } else {
        
      out.write("\r\n");
      out.write("        <p>Không có bất động sản từ các thành phố lớn hiện tại.</p>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("        const productList = document.getElementById(\"productList\");\r\n");
      out.write("        const prevButton = document.getElementById(\"prevButton\");\r\n");
      out.write("        const nextButton = document.getElementById(\"nextButton\");\r\n");
      out.write("\r\n");
      out.write("        // Function to scroll the product list by a set amount\r\n");
      out.write("        function scrollProductList(amount) {\r\n");
      out.write("            productList.scrollBy({\r\n");
      out.write("                left: amount,\r\n");
      out.write("                behavior: 'smooth'\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Event listeners for the buttons\r\n");
      out.write("        prevButton.addEventListener(\"click\", () => scrollProductList(-300));\r\n");
      out.write("        nextButton.addEventListener(\"click\", () => scrollProductList(300));\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"banner\">\r\n");
      out.write("    <img src=\"jpg/2833732387999181063.gif\" alt=\"Banner Image\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"product-section\">\r\n");
      out.write("    <h2>Bất động sản theo địa điểm</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"property-form\">\r\n");
      out.write("        <div class=\"city hcm\">\r\n");
      out.write("            <a href=\"property-HCM.jsp\" class=\"city-link\">\r\n");
      out.write("                <img src=\"jpg/HCM.jpg\" alt=\"TP.HCM\">\r\n");
      out.write("                <span class=\"city-name\">TP.HCM</span>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"other-cities\">\r\n");
      out.write("            <div class=\"city\">\r\n");
      out.write("                <a href=\"property-HaNoi.jsp\" class=\"city-link\">\r\n");
      out.write("                    <img src=\"jpg/HaNoi.jpg\" alt=\"Hà Nội\">\r\n");
      out.write("                    <span class=\"city-name\">Hà Nội</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"city\">\r\n");
      out.write("                <a href=\"property-DaNang.jsp\" class=\"city-link\">\r\n");
      out.write("                    <img src=\"jpg/DaNang.jpg\" alt=\"Đà Nẵng\">\r\n");
      out.write("                    <span class=\"city-name\">Đà Nẵng</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"city\">\r\n");
      out.write("                <a href=\"property-BinhDuong.jsp\" class=\"city-link\">\r\n");
      out.write("                    <img src=\"jpg/binhduong.jpg\" alt=\"Bình Dương\">\r\n");
      out.write("                    <span class=\"city-name\">Bình Dương</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"city\">\r\n");
      out.write("                <a href=\"property-DongNai.jsp\" class=\"city-link\">\r\n");
      out.write("                    <img src=\"jpg/DongNai.jpg\" alt=\"Đồng Nai\">\r\n");
      out.write("                    <span class=\"city-name\">Đồng Nai</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <style>\r\n");
      out.write("        .property-form {\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .city-link {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .city-name {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 10px; /* Khoảng cách từ đỉnh */\r\n");
      out.write("            left: 10px; /* Khoảng cách từ bên trái */\r\n");
      out.write("            color: white; /* Màu chữ */\r\n");
      out.write("            background-color: transparent; /* Nền bán trong suốt */\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            border-radius: 3px; /* Bo góc */\r\n");
      out.write("            font-size: 20px; /* Kích thước chữ */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .city-link:hover .city-name {\r\n");
      out.write("            text-decoration: underline; /* Gạch chân khi hover */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"footer-top\">\r\n");
      out.write("\r\n");
      out.write("        <h1><a href=\"homes\">\r\n");
      out.write("            <span class=\"color1\">HOME</span>\r\n");
      out.write("            <span class=\"color2\">LANDER</span>\r\n");
      out.write("        </a></h1>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-phone\"></i> Hotline: 0123 456 789</span>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-envelope\"></i> Hỗ trợ: support@batdongsan.com</span>\r\n");
      out.write("        <span class=\"footer-item\"><i class=\"fas fa-headset\"></i> Chăm sóc: 0987 654 321</span>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-content\">\r\n");
      out.write("        <!-- Thông tin công ty -->\r\n");
      out.write("        <div class=\"company-info\">\r\n");
      out.write("            <h3>Công ty Bất Động Sản</h3>\r\n");
      out.write("            <p>Địa chỉ: 123 Đường ABC, Quận 1, TP.HCM</p>\r\n");
      out.write("            <p>Điện thoại: 0123 456 789</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Liên kết nhanh -->\r\n");
      out.write("        <div class=\"quick-links\">\r\n");
      out.write("            <h3>Liên kết nhanh</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("                <li><a href=\"#\">Dự án</a></li>\r\n");
      out.write("                <li><a href=\"#\">Tin tức</a></li>\r\n");
      out.write("                <li><a href=\"#\">Liên hệ</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Mạng xã hội -->\r\n");
      out.write("        <div class=\"social-media\">\r\n");
      out.write("            <h3>Mạng xã hội</h3>\r\n");
      out.write("            <a href=\"https://www.facebook.com/khoa.ngo.562114/\" class=\"social-icon\"><i class=\"fab fa-facebook\"></i>\r\n");
      out.write("                Facebook</a>\r\n");
      out.write("            <a href=\"https://www.instagram.com/khoa5462/\" class=\"social-icon\"><i class=\"fab fa-instagram\"></i>\r\n");
      out.write("                Instagram</a>\r\n");
      out.write("            <a href=\"https://mail.google.com/mail/u/0/?hl=vi#inbox\" class=\"social-icon\"><i\r\n");
      out.write("                    class=\"fas fa-envelope\"></i>\r\n");
      out.write("                Mail</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Form nhập email -->\r\n");
      out.write("        <div class=\"newsletter\">\r\n");
      out.write("            <h3>Đăng ký nhận tin tức mới nhất</h3>\r\n");
      out.write("            <form action=\"#\" method=\"POST\">\r\n");
      out.write("                <input type=\"email\" name=\"email\" placeholder=\"Nhập email của bạn\" required>\r\n");
      out.write("                <button type=\"submit\">Đăng ký</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("        <p>&copy; 2024 Công ty Bất Động Sản. Mọi quyền lợi thuộc về công ty.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    .footer {\r\n");
      out.write("        background-color: whitesmoke;\r\n");
      out.write("        color: black;\r\n");
      out.write("        padding: 30px 50px; /* Thêm padding cho lề trái và phải */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Căn chỉnh các phần trong footer content thành một hàng */\r\n");
      out.write("    .footer-content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between; /* Giãn cách đều giữa các phần tử */\r\n");
      out.write("        align-items: flex-start; /* Căn chỉnh các phần tử theo chiều dọc */\r\n");
      out.write("        flex-wrap: wrap; /* Cho phép xuống dòng khi cần thiết trên màn hình nhỏ */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* Căn chỉnh mỗi phần tử trong footer */\r\n");
      out.write("    .footer-content > div {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("        min-width: 200px; /* Đảm bảo mỗi phần có ít nhất 200px */\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: flex-start; /* Căn theo chiều dọc */\r\n");
      out.write("        align-items: flex-start; /* Căn chỉnh nội dung theo lề trái */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-content > div:last-child {\r\n");
      out.write("        margin-right: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Các phần trong footer */\r\n");
      out.write("    .company-info, .quick-links, .social-media, .newsletter {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quick-links ul li a:hover,\r\n");
      out.write("    .social-media a:hover {\r\n");
      out.write("        color: darkred; /* Màu khi hover vào liên kết */\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h3 {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin-right: 0;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .u-lo li {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("        z-index: 10; /* Đảm bảo menu cha hiển thị trên cùng */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Thiết lập cho menu con */\r\n");
      out.write("    ul li ul {\r\n");
      out.write("        display: none; /* Ẩn menu con mặc định */\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 100%;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("        padding: 10px 0;\r\n");
      out.write("        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        z-index: 999; /* Đảm bảo menu con hiển thị trên các phần tử khác */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li ul li {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li ul li a {\r\n");
      out.write("        padding: 10px 15px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Hiển thị menu con khi hover */\r\n");
      out.write("    ul li:hover ul {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Style cho menu con khi hover */\r\n");
      out.write("    ul li ul li a:hover {\r\n");
      out.write("        background-color: #eee;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .social-media a {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Form nhập email */\r\n");
      out.write("    .newsletter form {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter input[type=\"email\"] {\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        width: 220px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter input[type=\"email\"]:focus {\r\n");
      out.write("        border-color: #f4a261;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button {\r\n");
      out.write("        padding: 8px 15px; /* Làm cho nút nhỏ hơn */\r\n");
      out.write("        font-size: 13px; /* Giảm kích thước chữ */\r\n");
      out.write("        background-color: #f4a261;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button:hover {\r\n");
      out.write("        background-color: #e38e3e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Responsive design */\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .footer-content {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-content > div {\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter form {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter input[type=\"email\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-bottom {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    let cartItems = JSON.parse(sessionStorage.getItem('cartItems')) || [];\r\n");
      out.write("    let miniCartVisible = false; // Biến theo dõi trạng thái hiển thị của giỏ hàng\r\n");
      out.write("\r\n");
      out.write("    // Hàm thêm bất động sản vào giỏ hàng\r\n");
      out.write("    function addToFavorites(id, title, price, area, imageUrl, address) {\r\n");
      out.write("        const existingProductIndex = cartItems.findIndex(item => item.id === id);\r\n");
      out.write("\r\n");
      out.write("        if (existingProductIndex !== -1) {\r\n");
      out.write("            alert(\"bất động sản này đã được quan tâm!\"); // Thông báo cho người dùng\r\n");
      out.write("        } else {\r\n");
      out.write("            const product = {\r\n");
      out.write("                id: id,\r\n");
      out.write("                title: title,\r\n");
      out.write("                price: parseFloat(price),\r\n");
      out.write("                area: area,\r\n");
      out.write("                imageUrl: imageUrl,\r\n");
      out.write("                address: address,\r\n");
      out.write("                quantity: 1 // Số lượng cố định là 1\r\n");
      out.write("            };\r\n");
      out.write("            cartItems.push(product);\r\n");
      out.write("            updateSessionStorage();\r\n");
      out.write("            updateCartDisplay();\r\n");
      out.write("            showMiniCart();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật sessionStorage\r\n");
      out.write("    function updateSessionStorage() {\r\n");
      out.write("        sessionStorage.setItem('cartItems', JSON.stringify(cartItems));\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật hiển thị giỏ hàng\r\n");
      out.write("    function updateCartDisplay() {\r\n");
      out.write("        const itemCount = document.querySelector('.item-count');\r\n");
      out.write("        const cartList = document.getElementById('cart-items');\r\n");
      out.write("\r\n");
      out.write("        cartList.innerHTML = '';\r\n");
      out.write("\r\n");
      out.write("        if (cartItems.length === 0) {\r\n");
      out.write("            cartList.innerHTML = '<li>Bạn chưa có bất động sản đã lưu.</li>';\r\n");
      out.write("            itemCount.innerText = 0; // Cập nhật số lượng sản phẩm\r\n");
      out.write("            return; // Kết thúc hàm nếu giỏ hàng trống\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        cartItems.forEach((item) => {\r\n");
      out.write("            const listItem = document.createElement('li');\r\n");
      out.write("            listItem.innerHTML = `\r\n");
      out.write("            <img src=\"${item.imageUrl}\" alt=\"${item.title}\" width=\"40\" height=\"40\">\r\n");
      out.write("            <div class=\"item-info\">\r\n");
      out.write("                <h4>${item.title}</h4>\r\n");
      out.write("                <p>Địa chỉ: ${item.address}</p>\r\n");
      out.write("                <p>Diện tích: ${item.area} m²</p>\r\n");
      out.write("                <span>Giá: ${item.price.toLocaleString()} tỷ</span>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <button onclick=\"removeFromCart('${item.id}')\">Xóa</button>\r\n");
      out.write("        `;\r\n");
      out.write("            cartList.appendChild(listItem);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        itemCount.innerText = cartItems.length; // Cập nhật số lượng sản phẩm\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Xóa sản phẩm khỏi giỏ hàng\r\n");
      out.write("    function removeFromCart(id) {\r\n");
      out.write("        cartItems = cartItems.filter(item => item.id !== id);\r\n");
      out.write("        updateSessionStorage();\r\n");
      out.write("        updateCartDisplay();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Hiện giỏ hàng mini\r\n");
      out.write("    function showMiniCart() {\r\n");
      out.write("        const miniCart = document.querySelector('.mini-cart');\r\n");
      out.write("        miniCart.style.display = 'block';\r\n");
      out.write("        updateCartDisplay();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Chuyển hướng đến trang giỏ hàng\r\n");
      out.write("    function goToCart() {\r\n");
      out.write("        const isLoggedIn = sessionStorage.getItem('isLoggedIn'); // Giả sử bạn kiểm tra trạng thái đăng nhập ở đây\r\n");
      out.write("\r\n");
      out.write("        if (!isLoggedIn) {\r\n");
      out.write("            alert(\"Bạn cần đăng nhập để xem bất động sản đã quan tâm.\"); // Thông báo cho người dùng\r\n");
      out.write("            window.location.href = 'login.jsp'; // Chuyển hướng đến trang đăng nhập\r\n");
      out.write("        } else {\r\n");
      out.write("            window.location.href = 'cart.jsp'; // Chuyển hướng đến trang giỏ hàng\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Cập nhật hiển thị giỏ hàng khi tải lại trang\r\n");
      out.write("    updateCartDisplay();\r\n");
      out.write("\r\n");
      out.write("    function toggleMiniCart() {\r\n");
      out.write("        const miniCart = document.querySelector('.mini-cart');\r\n");
      out.write("        miniCartVisible = !miniCartVisible; // Chuyển đổi trạng thái hiển thị\r\n");
      out.write("        miniCart.style.display = miniCartVisible ? 'block' : 'none'; // Cập nhật hiển thị\r\n");
      out.write("        updateCartDisplay(); // Cập nhật hiển thị giỏ hàng\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("    .footer-top {\r\n");
      out.write("        display: flex; /* Sử dụng flexbox để căn chỉnh */\r\n");
      out.write("        justify-content: space-around; /* Giãn cách đều giữa các mục */\r\n");
      out.write("        padding: 10px 0; /* Khoảng cách trên và dưới */\r\n");
      out.write("        margin-bottom: 20px; /* Khoảng cách dưới để tách khỏi nội dung footer */\r\n");
      out.write("        text-align: center; /* Căn giữa nội dung */\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-top h1 a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-item {\r\n");
      out.write("        margin: 0 15px; /* Khoảng cách giữa các mục */\r\n");
      out.write("        font-weight: bold; /* Chữ đậm */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* Các phần khác của footer giữ nguyên */\r\n");
      out.write("    .footer {\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        background-color: whitesmoke;\r\n");
      out.write("        color: black;\r\n");
      out.write("        padding: 30px 50px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-content {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: flex-start;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-content > div {\r\n");
      out.write("        flex: 1;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("        min-width: 200px;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        justify-content: flex-start;\r\n");
      out.write("        align-items: flex-start;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-content > div:last-child {\r\n");
      out.write("        margin-right: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .company-info, .quick-links, .social-media, .newsletter {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quick-links ul li a:hover,\r\n");
      out.write("    .social-media a:hover {\r\n");
      out.write("        color: darkred;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h3 {\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul {\r\n");
      out.write("        padding-left: 20px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul li a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .social-media a {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter form {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter input[type=\"email\"] {\r\n");
      out.write("        padding: 8px;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        width: 220px;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter input[type=\"email\"]:focus {\r\n");
      out.write("        border-color: #f4a261;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button {\r\n");
      out.write("        padding: 8px 15px;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        background-color: #f4a261;\r\n");
      out.write("        border: none;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .newsletter button:hover {\r\n");
      out.write("        background-color: #e38e3e;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @media (max-width: 768px) {\r\n");
      out.write("        .footer-content {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .footer-content > div {\r\n");
      out.write("            margin-right: 0;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter form {\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter input[type=\"email\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .newsletter button {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .footer-bottom {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: black;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .heart-container {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        padding-top: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .heart-icon1 {\r\n");
      out.write("        width: 15px; /* Kích thước của biểu tượng trái tim */\r\n");
      out.write("        height: 15px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
